#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
#                                        ----[ClansLite]----                                        #
#                                     ----[By Loving11ish]----                                      #
#                                  ----[Contributors: Gamlin]----                                   #
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
#                                   ----[Plugin Config File]----                                    #
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
# Clans config for ${version}
clan-size:
  #Set the default maximum amount of members that can join a players clan. [Default value: 8]
  default-max-clan-size: 8
  #To allow the use of a tiered permission system for clan sizes instead of the global amount, use the system below.
  tiered-clan-system:
    #Enable the tiered system use. [Default value: false]
    enabled: false
    permission-group-list:
      group-1: 4 #Perm: 'clanslite.maxclansize.group1' [This perm is given by default]
      group-2: 8 #Perm: 'clanslite.maxclansize.group2'
      group-3: 12 #Perm: 'clanslite.maxclansize.group3'
      group-4: 16 #Perm: 'clanslite.maxclansize.group4'
      group-5: 20 #Perm: 'clanslite.maxclansize.group5'
      group-6: 24 #Perm: 'clanslite.maxclansize.group6'


#Set the maximum amount of allied clans that can a clan can have. [Default value: 4]
max-clan-allies: 4

#Clan protections
protections:
  pvp:
    #Globally enable the clan friendly fire system. [Default value: true]
    pvp-command-enabled: true
    #Enable the ability for a player to bypass the pvp protection using 'clanslite.bypass.pvp'. [Default value: true]
    enable-bypass-permission: true

#Clan home system
clan-home:
  #Enable the '/clan [sethome|home]' system. [Default value: true]
  enabled: true
  cool-down:
    #Enable the cool down on the '/clan home' command to prevent tp spamming (RECOMMENDED). [Default value: true]
    enabled: true
    #Cool-down time in seconds. [Default value: 60 = 1 minute]
    time: 60

#ClansLite update system
plugin-update-notifications:
  #Do you want to enable in game plugin update notifications? (Permission:'clanslite.update'). [Default value: true]
  enabled: true